### ISSUE TITLE
comments without `--` are not identified as comments when multiline.

### ISSUE THREAD

**Issue by NullVoxPopuli** [alexlafroscia/tree-sitter-glimmer#100]
Test:
```hbs
<div
  {{! 
    this is a 
    multi-line comment
  }}
>
```

**Comment by alexlafroscia** [comment]
Is this format of comment supposed to be valid syntax? As far as I know, multi-line comments _need_ the `--` after the `!` but it's _very_ possible that's changed; it's been a long time since I was up-to-date on Ember-related stuff.

**Comment by NullVoxPopuli** [comment]
It is valid, yeah, for example:
https://limber.glimdown.com/edit?c=MQAgwg9gtlCmB2AXAzgKFQC0YgDsgXAPSEDmAlohgK4BGAdAMbSECGANrAB5ssBmAThGQMyLQon6xYAWmQVEsftJJsyMRYTLJkVWMkIBGAAxH0AAwskAVshCqAbrFQAeBVBw8FAPlQgQAFS5EXxAAb1CAQmlpEAAZCHgScGg4JBBogF8MkPCo6RC-ECgqNkQyVXhYOwSkpnU0kMzsv1zogr9i0vKySurEkDrUxBB2kHY2CAB3W3CQLJBJigwexukskMDOYJbIkGQMCH5hwYRh9Z2IkcKikrKKqv3D45TTkPOAoJDnPJAsKDYBi80tEfH5vm1rp07j0qn8ASckKsfM5xLB3J5YD4LGZUEA&format=glimdown

**Comment by alexlafroscia** [comment]
I see! Good to know!

**Comment by NullVoxPopuli** [comment]
This is resolved!
