### ISSUE TITLE
Some samples, so people can see what this looks like so far

### ISSUE THREAD

**Issue by NullVoxPopuli** [alexlafroscia/tree-sitter-glimmer#2]
This is the Edge theme with some customizations
![image](https://user-images.githubusercontent.com/199018/109427907-83654300-79c2-11eb-8c29-650f5bf9b16d.png)

**Comment by NullVoxPopuli** [comment]
a bug!
 - expressions in a string are colored goofy:
 
![image](https://user-images.githubusercontent.com/199018/109428107-844aa480-79c3-11eb-825d-db1b0e2e6a78.png)

**Comment by alexlafroscia** [comment]
@NullVoxPopuli would you mind opening a separate issue about the expressions-in-a-string bug? I definitely want to fix that! 

I think the problem is likely that I should be, but am probably not, matching multi-line strings correctly. Forgot that was "a thing"!

**Comment by alexlafroscia** [comment]
Rather than doing screenshots, I'm thinking about using the `tree-sitter highlight` command to generate a "live" docs site with example code highlighted by the actual grammar, that can be re-built automatically in CI and deployed to GitHub Pages. Then the examples stay in sync with the actual parser all the time. Thoughts?

**Comment by alexlafroscia** [comment]
I need to improve the color palette, but that was actually pretty easy!

https://alexlafroscia.github.io/tree-sitter-glimmer/

**Comment by NullVoxPopuli** [comment]
I like it! 

this is static, but I like all the examples so far!
Making it live would be kinda stellar :)

**Comment by alexlafroscia** [comment]
That's a really cool idea! I had had a similar thought; we could use the WASM build and make some examples people can flip through, plus let them edit the example "live". Sounds like a neat project!

**Comment by NullVoxPopuli** [comment]
Yeah! Though, I wonder how if we'd need to do a preview pane like typescript / babel, or if we can have a live editor with live coloring. I think highlight.js (or was it retype?) has a tree-sitter plugin, so if there is a way to live edit the html safely, I think we'll have something neat
