### ISSUE TITLE
How do I use this project?

### ISSUE THREAD

**Issue by pernambucano** [alexlafroscia/tree-sitter-glimmer#7]
Hi, thank you so much for all the effort being put into this. 

I'm a really noob regarding TS and I couldn't understand how to use this project alongside TS. Do I have to get the grammar and put it somewhere? I also couldn't find it on the :TSInstall list. 
Again, thanks a lot!

**Comment by pernambucano** [comment]
yep, got an old TS on my nvim. Sorry about that, you should find it under the name "glimmer".

**Comment by alexlafroscia** [comment]
Sorry about that!

With https://github.com/nvim-treesitter/nvim-treesitter/pull/985 things should "just work" if for the most part; the parser and highlighting is part of `nvim-treesitter`

I also have some instructions about using it more directly, which I wrote up before the PR referenced above was created

https://github.com/alexlafroscia/tree-sitter-glimmer/wiki/Highlighting-in-NeoVim
