### ISSUE TITLE
expressions in a string are colored goofy

### ISSUE THREAD

**Issue by NullVoxPopuli** [alexlafroscia/tree-sitter-glimmer#8]
![image](https://user-images.githubusercontent.com/199018/109901436-13c3b200-7c67-11eb-92c4-5ffe2de6ed19.png)

**Comment by alexlafroscia** [comment]
Is this still a problem? I (tried to) add support for Mustache statements inside of strings in this commit

https://github.com/alexlafroscia/tree-sitter-glimmer/commit/423389c260ba7b29edf7e65b863e3e18ca9b822a

**Comment by alexlafroscia** [comment]
I realize what happened -- I started support for this with a trivial use-case that I _meant_ to progress to more complex cases, but didn't!

This should actually work as expected now. I also added the `concat_statement` to the highlighter (which we'll need to up-stream to `nvim-treesitter` at some point, too, but I have other changes planned that we should make all at once)

**Comment by NullVoxPopuli** [comment]
I don't know what's happened. lol

![image](https://user-images.githubusercontent.com/199018/110027503-0eff0c80-7d00-11eb-9206-028beab1fb53.png)

Did I mess up a config?
https://github.com/NullVoxPopuli/dotfiles/commit/a959a44ac38529b6227f48a5717fa324c1dd96d4#diff-620f1f101ce7e33069322d80c18352989f279b536e3d43364ee16b0d7d982f38R16

I'm launching with `GLIMMER_DEBUG=true nvim .`

**Comment by NullVoxPopuli** [comment]
oh, it just started working 

![image](https://user-images.githubusercontent.com/199018/110029723-d01e8600-7d02-11eb-81b2-43334c05a75d.png)
noice

**Comment by alexlafroscia** [comment]
Great!

A lot of improvements landed today -- let me know what you think!
